name: Generate Snake Grid

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: actions/upload-artifact@v3
        with:
          name: contribution-grid
          path: dist/github-contribution-grid-snake.svg
